# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

heavy_parameter_transformR <- function(parameters, K, p, q, O, A, B, pMax1, qMax1) {
    invisible(.Call('_highfrequency_heavy_parameter_transformR', PACKAGE = 'highfrequency', parameters, K, p, q, O, A, B, pMax1, qMax1))
}

heavy_parameter_transform_RetrackR <- function(parameters, K, p, q, means, O, A, B, pMax1, qMax1) {
    invisible(.Call('_highfrequency_heavy_parameter_transform_RetrackR', PACKAGE = 'highfrequency', parameters, K, p, q, means, O, A, B, pMax1, qMax1))
}

heavy_likelihoodR <- function(parameters, data, T1, K1, means, p, q, pMax1, qMax1, backcast, LB, UB, compconst1, h, lls, llRM, ll) {
    invisible(.Call('_highfrequency_heavy_likelihoodR', PACKAGE = 'highfrequency', parameters, data, T1, K1, means, p, q, pMax1, qMax1, backcast, LB, UB, compconst1, h, lls, llRM, ll))
}

nsmaller <- function(times, lengths, start, end, max) {
    .Call('_highfrequency_nsmaller', PACKAGE = 'highfrequency', times, lengths, start, end, max)
}

