# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

har_agg <- function(RM, periods, iNperiods) {
    .Call(`_highfrequency_har_agg`, RM, periods, iNperiods)
}

calcRecVarEq <- function(par, rm) {
    .Call(`_highfrequency_calcRecVarEq`, par, rm)
}

quadraticKernel <- function(x) {
    .Call(`_highfrequency_quadraticKernel`, x)
}

tradeIntensityProcessCpp <- function(time, bandwidth) {
    .Call(`_highfrequency_tradeIntensityProcessCpp`, time, bandwidth)
}

AsymptoticVarianceC <- function(vIn, iLag) {
    .Call(`_highfrequency_AsymptoticVarianceC`, vIn, iLag)
}

AutomaticLagSelectionC <- function(vX, dMu) {
    .Call(`_highfrequency_AutomaticLagSelectionC`, vX, dMu)
}

DriftBurstLoopC <- function(vPreAveraged, diffedlogprices, vTime, vTesttime, iMeanBandwidth, iVarBandwidth, iPreAverage, iAcLag) {
    .Call(`_highfrequency_DriftBurstLoopC`, vPreAveraged, diffedlogprices, vTime, vTesttime, iMeanBandwidth, iVarBandwidth, iPreAverage, iAcLag)
}

DriftBurstLoopCPAR <- function(vPreAveraged, diffedlogprices, vTime, vTesttime, iMeanBandwidth, iVarBandwidth, iPreAverage, iAcLag, iCores) {
    .Call(`_highfrequency_DriftBurstLoopCPAR`, vPreAveraged, diffedlogprices, vTime, vTesttime, iMeanBandwidth, iVarBandwidth, iPreAverage, iAcLag, iCores)
}

#' @keywords internal
NULL

#' @keywords internal
colCumsum <- function(x) {
    .Call(`_highfrequency_colCumsum`, x)
}

#' @keywords internal
refreshTimeMatching <- function(x, idx) {
    .Call(`_highfrequency_refreshTimeMatching`, x, idx)
}

#' @keywords internal
preAveragingReturnsInternal <- function(ret, kn) {
    .Call(`_highfrequency_preAveragingReturnsInternal`, ret, kn)
}

findFirst <- function(x, thresh) {
    .Call(`_highfrequency_findFirst`, x, thresh)
}

overlap <- function(min1, max1, min2, max2) {
    .Call(`_highfrequency_overlap`, min1, max1, min2, max2)
}

mSeq <- function(starts, ends, scaleFactor) {
    .Call(`_highfrequency_mSeq`, starts, ends, scaleFactor)
}

cfilter <- function(x, filter) {
    .Call(`_highfrequency_cfilter`, x, filter)
}

mldivide <- function(A, B) {
    .Call(`_highfrequency_mldivide`, A, B)
}

rollApplyMinWrapper <- function(x) {
    .Call(`_highfrequency_rollApplyMinWrapper`, x)
}

rollApplyMedianWrapper <- function(x) {
    .Call(`_highfrequency_rollApplyMedianWrapper`, x)
}

rollApplyProdWrapper <- function(x, m) {
    .Call(`_highfrequency_rollApplyProdWrapper`, x, m)
}

tickGrouping_RETURNS <- function(end, size) {
    .Call(`_highfrequency_tickGrouping_RETURNS`, end, size)
}

leadLagCpp <- function(x, timestampsX, y, timestampsY, lags, normalize) {
    .Call(`_highfrequency_leadLagCpp`, x, timestampsX, y, timestampsY, lags, normalize)
}

leadLagCppPAR <- function(x, timestampsX, y, timestampsY, lags, normalize, iCores) {
    .Call(`_highfrequency_leadLagCppPAR`, x, timestampsX, y, timestampsY, lags, normalize, iCores)
}

nsmaller <- function(times, lengths, start, end, max) {
    .Call(`_highfrequency_nsmaller`, times, lengths, start, end, max)
}

KK <- function(x, type) {
    .Call(`_highfrequency_KK`, x, type)
}

kernelEstimator <- function(a, b, na, q, adj, type, ab, ab2) {
    .Call(`_highfrequency_kernelEstimator`, a, b, na, q, adj, type, ab, ab2)
}

pcovcc <- function(a, ap, b, at, atp, bt, na, nap, nb, period) {
    .Call(`_highfrequency_pcovcc`, a, ap, b, at, atp, bt, na, nap, nb, period)
}

bacImpliedBetaHYCpp <- function(components, missings, componentWeights) {
    .Call(`_highfrequency_bacImpliedBetaHYCpp`, components, missings, componentWeights)
}

bacImpliedBetaCpp <- function(components, missings, componentWeights) {
    .Call(`_highfrequency_bacImpliedBetaCpp`, components, missings, componentWeights)
}

bacHY <- function(component, ETF, missingComponent, missingETF, componentWeightings) {
    .Call(`_highfrequency_bacHY`, component, ETF, missingComponent, missingETF, componentWeightings)
}

