# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nsmaller <- function(times, lengths, start, end, max) {
    .Call('_highfrequency_nsmaller', PACKAGE = 'highfrequency', times, lengths, start, end, max)
}

